# Generated by Django 4.2.7 on 2025-05-07 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ride_management', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='dropoff_location_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_location_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ride_management.driver'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dropoff_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_as_dropoff', to='ride_management.location'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='estimated_arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='fare',
            field=models.DecimalField(decimal_places=2, default=150.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='pickup_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_as_pickup', to='ride_management.location'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ride_management.vehicle'),
        ),
    ]
